language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: raUwaUh2eK0hsGCypld+8DO0iix48sXifvQ0EBwRWJH+FLyfggSkRZ6xAQedEvSnxIJvNJDRLr2ILZOl2cZRPjXJVIyTwByoRd9qgKpBlJCBDVw57G1ei3/QPw5juVqjxI0dfycC8/wZKvpMQbTcsuXeePgUBauXezE8PwH8A66fWo8E3ZkkQg2JlJJE1ZmkDAtkn7Cev5Ee7rDwF+0rCVx1a7dUyRU98PzOiLddBnFtLCPyb3PIeb/zSOniunDk/DCgjU2+BqQHTyLBi3nfcQJeDEj9cCAh7rpv54Fs+XOIO5DC4U2Zcaahi9d3F2MMcJaheccobDYHUHIoYK9Y20j6ksdVpnxBjnXVBchxaS41LirkijH1aQhOoRppHxRDEmyWh2CZGnWOTgiw2TQhAXLjxQBefyQBk+Q5w78EAWq0xm3oakltBnIBR7hakx+4ho5TYTXk6YcsYq16D3fAN9er7eko0I3hBDa4sFss56l58Hz8sSc6iA2o7EYOlrCYyDyF4T/odbxT8R6/NVA0euBdEzhiWrVFakiUafqQvbL8Pu+7OpKYLR02lqZvKK9nmdx4HSjXJYIDJufUv0WXmJLiK1QNqKUcO6IaxNyLcw5HQZbGp+UWWuHP0i6BFLoXoagU4A89RS1V98QnTrdTFjdR6K4iZqwma7EsakgRqHI=
